EHOKU/Controllers/RolaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace EHOKU.Controllers
{
    public class RolaController : Controller
    {
        private EHOKUEntities db = new EHOKUEntities();

        // GET: Rola
        public ActionResult Index()
        {
            return View(db.ROLA.ToList());
        }

        // GET: Rola/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ROLA rOLA = db.ROLA.Find(id);
            if (rOLA == null)
            {
                return HttpNotFound();
            }
            return View(rOLA);
        }

        // GET: Rola/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Rola/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_ROLA,OPIS,NAPOMENA")] ROLA rOLA)
        {
            if (ModelState.IsValid)
            {
                db.ROLA.Add(rOLA);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(rOLA);
        }

        // GET: Rola/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ROLA rOLA = db.ROLA.Find(id);
            if (rOLA == null)
            {
                return HttpNotFound();
            }
            return View(rOLA);
        }

        // POST: Rola/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_ROLA,OPIS,NAPOMENA")] ROLA rOLA)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rOLA).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(rOLA);
        }

        // GET: Rola/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ROLA rOLA = db.ROLA.Find(id);
            if (rOLA == null)
            {
                return HttpNotFound();
            }
            return View(rOLA);
        }

        // POST: Rola/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(decimal id)
        {
            ROLA rOLA = db.ROLA.Find(id);
            db.ROLA.Remove(rOLA);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EHOKU/Controllers/STATUS_POSLAController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace EHOKU.Controllers
{
    public class STATUS_POSLAController : Controller
    {
        private EHOKUEntities db = new EHOKUEntities();

        // GET: STATUS_POSLA
        public ActionResult Index()
        {
            return View(db.STATUS_POSLA.ToList());
        }

        // GET: STATUS_POSLA/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            STATUS_POSLA sTATUS_POSLA = db.STATUS_POSLA.Find(id);
            if (sTATUS_POSLA == null)
            {
                return HttpNotFound();
            }
            return View(sTATUS_POSLA);
        }

        // GET: STATUS_POSLA/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: STATUS_POSLA/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_STATUS_POSLA,OPIS,NAPOMENA")] STATUS_POSLA sTATUS_POSLA)
        {
            if (ModelState.IsValid)
            {
                db.STATUS_POSLA.Add(sTATUS_POSLA);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sTATUS_POSLA);
        }

        // GET: STATUS_POSLA/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            STATUS_POSLA sTATUS_POSLA = db.STATUS_POSLA.Find(id);
            if (sTATUS_POSLA == null)
            {
                return HttpNotFound();
            }
            return View(sTATUS_POSLA);
        }

        // POST: STATUS_POSLA/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_STATUS_POSLA,OPIS,NAPOMENA")] STATUS_POSLA sTATUS_POSLA)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sTATUS_POSLA).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sTATUS_POSLA);
        }

        // GET: STATUS_POSLA/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            STATUS_POSLA sTATUS_POSLA = db.STATUS_POSLA.Find(id);
            if (sTATUS_POSLA == null)
            {
                return HttpNotFound();
            }
            return View(sTATUS_POSLA);
        }

        // POST: STATUS_POSLA/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(decimal id)
        {
            STATUS_POSLA sTATUS_POSLA = db.STATUS_POSLA.Find(id);
            db.STATUS_POSLA.Remove(sTATUS_POSLA);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EHOKU/Views/STATUS_POSLA/Create.cshtml
@model EHOKU.Controllers.STATUS_POSLA

@{
    ViewBag.Title = "Create";
    Layout = null;
}



@*@using (Html.BeginForm()) 
{*@
@using (Html.BeginForm("Create", "STATUS_POSLA", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    
    <div class="row">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            <label class="col-md-3 control-label">Status posla:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.ID_STATUS_POSLA, new { htmlAttributes = new { @class = "form-control", placeholder = "Status posla" } })
                @Html.ValidationMessageFor(model => model.ID_STATUS_POSLA, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <label class="col-md-3 control-label">Status posla:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.OPIS, new { htmlAttributes = new { @class = "form-control", placeholder = "Status posla" } })
                @Html.ValidationMessageFor(model => model.OPIS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Napomena:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.NAPOMENA, new { htmlAttributes = new { @class = "form-control", placeholder = "Dodatna napomena" } })
                @Html.ValidationMessageFor(model => model.NAPOMENA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-6">
                <br>
                <input type="submit" value="Izradi status posla" class="btn btn-success btn-block" />
            </div>
        </div>
    </div>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EHOKU/Views/STATUS_POSLA/Delete.cshtml
@model EHOKU.Controllers.STATUS_POSLA

@{
    ViewBag.Title = "Delete";
    Layout = null;
}

<div>

    <dl class="dl-horizontal">
        <dt>
            Opis statusa:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OPIS)
        </dd>

        <dt>
            Napomena:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NAPOMENA)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        <br />
        <div class="form-actions no-color col-md-offset-3 col-md-6">
            <input type="submit" value="Brisanje" class="btn btn-success btn-block" />
            @*@Html.ActionLink("Back to List", "Index")*@
        </div>
        <br />
        <br />
    }
</div>

EHOKU/Views/STATUS_POSLA/Details.cshtml
@model EHOKU.Controllers.STATUS_POSLA

@{
    ViewBag.Title = "Details";
    Layout = null;
}

<div>

    <dl class="dl-horizontal">
        <dt>
            Opis:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OPIS)
        </dd>

        <dt>
            Napomena:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NAPOMENA)
        </dd>

    </dl>
</div>
@*<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_STATUS_POSLA }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@

EHOKU/Views/STATUS_POSLA/Edit.cshtml
@model EHOKU.Controllers.STATUS_POSLA

@{
    ViewBag.Title = "Edit";
    Layout = null;
}



@*@using (Html.BeginForm())
{*@
@using (Html.BeginForm("Edit", "STATUS_POSLA", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_STATUS_POSLA)

        <div class="form-group">
            <label class="col-md-3 control-label">Opis statusa:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.OPIS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OPIS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Napomena:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.NAPOMENA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NAPOMENA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-6">
                <br>
                <input type="submit" value="Spremi promjene" class="btn btn-success btn-block" />
            </div>
        </div>
    </div>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EHOKU/Views/STATUS_POSLA/Index.cshtml
@model IEnumerable<EHOKU.Controllers.STATUS_POSLA>

@{
    ViewBag.Title = "Index";
}

@*<h2>Index</h2>*@
@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@

<br>
<br>
<br>
<br>
<br>
<br>
<p>
    @*<a href="@Url.Action("Create", "Rola")" class="btn btn-success">
            Unos nove privilegije
        </a>*@
    <button class="btn btn-default btn-block btn-lg" onclick="create()">Unos novog statusa</button>
</p>

<br>

<script>
    function create() {


        $.ajax({

            url: '/STATUS_POSLA/Create',

            success: function (data) {

                $('#modalWrapper').html(data);
                $('#myModal').modal({ backdrop: 'static' });
            }
        });
    }



    function edit(id) {


        $.ajax({

            url: '/STATUS_POSLA/Edit/' + id,

            success: function (data) {

                $('#modalWrapper').html(data);
                $('#myModal').modal({ backdrop: 'static' });
            }
        });
    }

    function del(id) {


        $.ajax({

            url: '/STATUS_POSLA/Delete/' + id,

            success: function (data) {

                $('#modalWrapper').html(data);
                $('#myModal').modal({ backdrop: 'static' });
            }
        });
    }

    function details(id) {


        $.ajax({

            url: '/STATUS_POSLA/Details/' + id,

            success: function (data) {

                $('#modalWrapper').html(data);
                $('#myModal').modal({ backdrop: 'static' });
            }
        });
    }
</script>


<div class="well">
    <div class="table-responsive-vertical shadow-z-1">
        <table id="table" class="table table-hover table-mc-light-blue table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.OPIS)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.NAPOMENA)
                    </th>
                </tr>
            </thead>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.OPIS)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NAPOMENA)
                    </td>
                    <td>
                        <button class="btn btn-default btn-xs" onclick=@string.Format("edit({0})", item.ID_STATUS_POSLA)>Uredi</button>
                        <button class="btn btn-default btn-xs" onclick=@string.Format("details({0})", item.ID_STATUS_POSLA)>Detalji</button>
                        <button class="btn btn-default btn-xs" onclick=@string.Format("del({0})", item.ID_STATUS_POSLA)>Brisanje</button>

                        @*@Html.ActionLink("Edit", "Edit", new { id=item.ID_ROLA }) |
                            @Html.ActionLink("Details", "Details", new { id=item.ID_ROLA }) |
                            @Html.ActionLink("Delete", "Delete", new { id=item.ID_ROLA })*@
                    </td>
                </tr>
            }


        </table>
    </div>
</div>






<!-- Modal -->
<div id="myModal" class="modal fade modal-wide" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Status posla</h4>
            </div>
            <div class="modal-body">

                @*@{Html.RenderAction("Create", "VrstaSpisa");}*@
                <div id="modalWrapper"></div>

            </div>

            @*<div class="modal-footer">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                        <div>
                            @Html.ActionLink("Back to List", "Index")
                        </div>
                    </div>
                </div>*@
        </div>

    </div>
</div>

<style>
    .well {
        border-radius: 0;
        -webkit-box-shadow: none;
        box-shadow: 0px 1px 10px rgba(0, 0, 0, 0.4);
</style>