EHOKU/Models/Osoba.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EHOKU.Models
{
    public class Osoba
    {
        public string ID { get; set; }
        public string IME { get; set; }
        public string ROLA { get; set; }

        public static Osoba Currentuser
        {
            get
            {
                if (HttpContext.Current.Session["LogedUser"] != null)
                {
                    return (Osoba)HttpContext.Current.Session["LogedUser"];
                }
                else
                {
                    return null;
                }
            }
            set
            {
                HttpContext.Current.Session["currentuser"] = value;
            }
        }


    }
}

EHOKU/Controllers/OsobaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace EHOKU.Controllers
{
    public class OsobaController : Controller
    {
        private EHOKUEntities db = new EHOKUEntities();

        // GET: Osoba
        public ActionResult Index()
        {
            var oSOBA = db.OSOBA.Include(o => o.ROLA);
            return View(oSOBA.ToList());
        }

        // GET: Osoba/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OSOBA oSOBA = db.OSOBA.Find(id);
            if (oSOBA == null)
            {
                return HttpNotFound();
            }
            return View(oSOBA);
        }

        // GET: Osoba/Create
        public ActionResult Create()
        {
            ViewBag.ID_ROLA = new SelectList(db.ROLA, "ID_ROLA", "OPIS");
            return View();
        }

        // POST: Osoba/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_OSOBA,OIB,IME,PREZIME,SPOL,KONTAKT_BROJ,EMAIL,ID_ROLA,ULICA,NASELJE,MJESTO")] OSOBA oSOBA)
        {
            if (ModelState.IsValid)
            {
                db.OSOBA.Add(oSOBA);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_ROLA = new SelectList(db.ROLA, "ID_ROLA", "OPIS", oSOBA.ID_ROLA);
            return View(oSOBA);
        }

        // GET: Osoba/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OSOBA oSOBA = db.OSOBA.Find(id);
            if (oSOBA == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_ROLA = new SelectList(db.ROLA, "ID_ROLA", "OPIS", oSOBA.ID_ROLA);
            return View(oSOBA);
        }

        // POST: Osoba/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_OSOBA,OIB,IME,PREZIME,SPOL,KONTAKT_BROJ,EMAIL,ID_ROLA,ULICA,NASELJE,MJESTO")] OSOBA oSOBA)
        {
            if (ModelState.IsValid)
            {
                db.Entry(oSOBA).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_ROLA = new SelectList(db.ROLA, "ID_ROLA", "OPIS", oSOBA.ID_ROLA);
            return View(oSOBA);
        }

        // GET: Osoba/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OSOBA oSOBA = db.OSOBA.Find(id);
            if (oSOBA == null)
            {
                return HttpNotFound();
            }
            return View(oSOBA);
        }

        // POST: Osoba/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(decimal id)
        {
            OSOBA oSOBA = db.OSOBA.Find(id);
            db.OSOBA.Remove(oSOBA);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EHOKU/Views/Osoba/Create.cshtml
@model EHOKU.Controllers.OSOBA

@{
    ViewBag.Title = "Create";
    Layout = null;
}




@*@using (Html.BeginForm()) 
{*@

@using (Html.BeginForm("Create", "Osoba", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    
    @*<div class="form-horizontal">*@
    <div class="row">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
                @Html.LabelFor(model => model.ID_OSOBA, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ID_OSOBA, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ID_OSOBA, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <h5 align="center">Osnovni podaci</h5>

        <div class="form-group">
            <label class="col-md-3 control-label">OIB:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.OIB, new { htmlAttributes = new { @class = "form-control", type = "text", placeholder = "Osobni Identifikacijski Broj" } })
                @Html.ValidationMessageFor(model => model.OIB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Ime:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.IME, new { htmlAttributes = new { @class = "form-control", placeholder = "Ime" } })
                @Html.ValidationMessageFor(model => model.IME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Prezime:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.PREZIME, new { htmlAttributes = new { @class = "form-control", placeholder = "Prezime" } })
                @Html.ValidationMessageFor(model => model.PREZIME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Privilegije:</label>
            <div class="col-md-6">
                @Html.DropDownList("ID_ROLA", null, htmlAttributes: new { @class = "form-control" }, optionLabel: "Odaberite privilegiju")
                @Html.ValidationMessageFor(model => model.ID_ROLA, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr />
        <h5 align="center">Dodatni podaci</h5>
        <div class="form-group">
            <label class="col-md-3 control-label">Spol:</label>
            <div class="col-md-6">
                @*@Html.EditorFor(model => model.SPOL, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.RadioButtonFor(model => model.SPOL, "M", false)@Html.Label("Muško")
                @Html.RadioButtonFor(model => model.SPOL, "Ž", false)@Html.Label("Žensko")
                @Html.ValidationMessageFor(model => model.SPOL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Kontakt broj:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.KONTAKT_BROJ, new { htmlAttributes = new { @class = "form-control", placeholder = "Kontakt broj" } })
                @Html.ValidationMessageFor(model => model.KONTAKT_BROJ, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">E-mail:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control", placeholder = "E-mail" } })
                @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr />
        <h5 align="center" >Podaci o lokaciji osobe</h5>
        <div class="form-group">
            <label class="col-md-3 control-label">Ulica:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.ULICA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ULICA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Naselje:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.NASELJE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NASELJE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Mjesto:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.MJESTO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MJESTO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Latitude:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.LATITUDE, new { htmlAttributes = new { @class = "form-control", placeholder = "XX.XXXXXXXXXX" } })
                @Html.ValidationMessageFor(model => model.MJESTO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Longitude:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.LONGITUDE, new { htmlAttributes = new { @class = "form-control", placeholder = "YY.YYYYYYYYYYY" } })
                @Html.ValidationMessageFor(model => model.MJESTO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-6">
                <br>
                <input type="submit" value="Izradi osobu" class="btn btn-success btn-block" />
            </div>
        </div>
    </div>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EHOKU/Views/Osoba/Edit.cshtml
@model EHOKU.Controllers.OSOBA

@{
    ViewBag.Title = "Edit";
    Layout = null;
}



@using (Html.BeginForm("Edit", "Osoba", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_OSOBA)

        <hr />
        <h5 align="center">Osnovni podaci</h5>
        <div class="form-group">
            <label class="col-md-3 control-label">OIB:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.OIB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OIB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Ime:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.IME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Prezime:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.PREZIME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PREZIME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Privilegija:</label>
            <div class="col-md-6">
                @Html.DropDownList("ID_ROLA", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_ROLA, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr />
        <h5 align="center">Dodatni podaci</h5>
        <div class="form-group">
            <label class="col-md-3 control-label">Spol:</label>
            <div class="col-md-6">
                @*@Html.EditorFor(model => model.SPOL, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.RadioButtonFor(model => model.SPOL, "M", false)@Html.Label("Muško")
                @Html.RadioButtonFor(model => model.SPOL, "Ž", false)@Html.Label("Žensko")
                @Html.ValidationMessageFor(model => model.SPOL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Kontakt broj:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.KONTAKT_BROJ, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KONTAKT_BROJ, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">E-mail:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr />
        <h5 align="center">Podaci o lokaciji osobe</h5>
        <div class="form-group">
            <label class="col-md-3 control-label">Ulica:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.ULICA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ULICA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Naselje:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.NASELJE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NASELJE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Mjesto:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.MJESTO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MJESTO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-6">
                <input type="submit" value="Spremi promjene" class="btn btn-success btn-block" />
            </div>
        </div>
        <br />
    </div>
}






@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EHOKU/Views/Osoba/Index.cshtml
@model IEnumerable<EHOKU.Controllers.OSOBA>

@{
    ViewBag.Title = "Index";
}

@*<h2>Pregled osoba</h2>*@

<br>
<br>
<br>

<p>
    @*@Html.ActionLink("Dodaj novu osobu", "Create")*@

    @*<a href="@Url.Action("Create", "Osoba")" class="btn btn-success">
        Unos nove osobe
    </a>*@
    <button class="btn btn-default btn-lg btn-block"  onclick="createOsoba()">Unos nove osobe</button>
</p>

<script>
    function createOsoba() {


        $.ajax({

            url: '/Osoba/Create' ,

            success: function (data) {

                $('#modalWrapper').html(data);
                $('#myModal').modal({ backdrop: 'static' });
            }
        });
    }



    function editOsoba(id) {


        $.ajax({

            url: '/Osoba/Edit/' + id,

            success: function (data) {

                $('#modalWrapper').html(data);
                $('#myModal').modal({ backdrop: 'static' });
            }
        });
    }

    function deleteOsoba(id) {


        $.ajax({

            url: '/Osoba/Delete/' + id,

            success: function (data) {

                $('#modalWrapper').html(data);
                $('#myModal').modal({ backdrop: 'static' });
            }
        });
    }

    function detailsOsoba(id) {


        $.ajax({

            url: '/Osoba/Details/' + id,

            success: function (data) {

                $('#modalWrapper').html(data);
                $('#myModal').modal({ backdrop: 'static' });
            }
        });
    }
</script>

<br>
<br>

<div class="container-fluid okvir">
    <div class="row">
        <!-- Pricing -->

@foreach (var item in Model)
{

        <div class="col-md-3">
            <div class="pricing hover-effect">
                <div class="pricing-head">
                    <h3>
                        @Html.DisplayFor(modelItem => item.PREZIME)  @Html.DisplayFor(modelItem => item.IME)
                         <span>
                             *****
                        </span>
                    </h3>
                    <h4>
                       <i> @Html.DisplayFor(modelItem => item.OIB)</i>
                        <span>
                            @Html.DisplayFor(modelItem => item.ROLA.OPIS)
                        </span>
                    </h4>
                </div>

                <ul class="pricing-content list-unstyled">
                    <li>
                        Kontakt: @Html.DisplayFor(modelItem => item.KONTAKT_BROJ)
                    </li>
                    <li>
                        E-mail: @Html.DisplayFor(modelItem => item.EMAIL)
                    </li>
                </ul>

                <div class="pricing-footer">
                    <p>
                       
                    </p>
                    <div>
                        <button class="btn btn-default btn-block" onclick=@string.Format("editOsoba({0})", item.ID_OSOBA)>Uredi podatke</button>
                    </div>
                    <div>
                        <button class="btn btn-default btn-block" onclick=@string.Format("detailsOsoba({0})", item.ID_OSOBA)>Pregledaj detalje</button>
                    </div>
                    <div>
                        <button class="btn btn-default btn-block" onclick=@string.Format("deleteOsoba({0})", item.ID_OSOBA)>Obriši osobu</button>
                    </div>
                </div>
            </div>
        </div>
}
        <!--//End Pricing -->
    </div>
</div>



<!-- Modal -->
<div id="myModal" class="modal fade" role="form">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Osoba</h4>
            </div>
            <div class="modal-body">

                @*@{Html.RenderAction("Create", "VrstaSpisa");}*@
                <div id="modalWrapper"></div>

            </div>

            @*<div class="modal-footer">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                        <div>
                            @Html.ActionLink("Back to List", "Index")
                        </div>
                    </div> proba
                </div>*@
        </div>

    </div>
</div>

<br>
<br>
<center>
    <strong>Powered by <a href="http://www.google.com" target="_blank">eHO-KU, kortikultura</a></strong>
</center>
<br>
<br>

<style>
/***
Pricing table
***/
.pricing {
  position: relative;
  margin-bottom: 15px;
  border: 3px solid #eee;
}

.pricing-active {
  /*border: 3px solid #36d7ac;*/
  border: 3px solid #23b04b;
  margin-top: -10px;
  box-shadow: 7px 7px rgba(54, 215, 172, 0.2);
}

.pricing:hover {
  /*border: 3px solid #36d7ac;*/
  border: 3px solid #23b04b;
}

.pricing:hover h4 {
  /*color: #36d7ac;*/
  color: #23b04b;

}

.pricing-head {
  text-align: center;
}

.pricing-head h3,
.pricing-head h4 {
  margin: 0;
  line-height: normal;
}

.pricing-head h3 span,
.pricing-head h4 span {
  display: block;
  margin-top: 5px;
  font-size: 14px;
  font-style: italic;
}

.pricing-head h3 {
  font-weight: 300;
  color: #fafafa;
  padding: 12px 0;
  font-size: 27px;
  /*background: #36d7ac;*/
  background: #23b04b;
  border-bottom: solid 1px #41b91c;
}

.pricing-head h4 {
  color: #bac39f;
  padding: 5px 0;
  font-size: 54px;
  font-weight: 300;
  background: #ffffff;
  border-bottom: solid 1px #f5f9e7;
}

.pricing-head-active h4 {
  /*color: #36d7ac;*/
  color: #23b04b;
}

.pricing-head h4 i {
  top: -8px;
  font-size: 28px;
  font-style: normal;
  position: relative;
}

.pricing-head h4 span {
  top: -10px;
  font-size: 14px;
  font-style: normal;
  position: relative;
}

/*Pricing Content*/
.pricing-content li {
  color: #888;
  font-size: 12px;
  padding: 7px 15px;
  border-bottom: solid 1px #f5f9e7;
  background: #ffffff;
}

/*Pricing Footer*/
.pricing-footer {
  color: #777;
  font-size: 11px;
  line-height: 17px;
  text-align: center;
  padding: 1 20px 19px;
  background: #ffffff;
}

/*Priceing Active*/
.price-active,
.pricing:hover {
  z-index: 9;
}

.price-active h4 {
  /*color: #36d7ac;*/
  color: #23b04b;
}

.no-space-pricing .pricing:hover {
  transition: box-shadow 0.2s ease-in-out;
}

.no-space-pricing .price-active .pricing-head h4,
.no-space-pricing .pricing:hover .pricing-head h4 {
  /*color: #36d7ac;*/
  color: #23b04b;
  padding: 15px 0;
  font-size: 80px;
  transition: color 0.5s ease-in-out;
}

.yellow-crusta.btn {
  color: #FFFFFF;
  background-color: #f3c200;
}
.yellow-crusta.btn:hover,
.yellow-crusta.btn:focus,
.yellow-crusta.btn:active,
.yellow-crusta.btn.active {
    color: #FFFFFF;
    background-color: #cfa500;
}

.okvir {
padding-left: 0px; 
padding-right: 0px
}


</style>

EHOKU/Views/Osoba/Index_backup.cshtml
@model IEnumerable<EHOKU.Controllers.OSOBA>

@{
    ViewBag.Title = "Index";
}

@*<h2>Pregled osoba</h2>*@

<br>
<br>
<br>

<p>
    @*@Html.ActionLink("Dodaj novu osobu", "Create")*@

    <a href="@Url.Action("Create", "Osoba")" class="btn btn-success">
        Unos nove osobe
    </a>
    <button class="btn btn-success" onclick="create()">Unos nove osobe</button>
</p>

<script>
    function create() {


        $.ajax({

            url: '/Osoba/Create' ,

            success: function (data) {

                $('#modalWrapper').html(data);
                $('#myModal').modal({ backdrop: 'static' });
            }
        });
    }



    function edit(id) {


        $.ajax({

            url: '/Osoba/Edit/' + id,

            success: function (data) {

                $('#modalWrapper').html(data);
                $('#myModal').modal({ backdrop: 'static' });
            }
        });
    }
</script>



@*<table class="table  table-bordered table-hover table-responsive table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OIB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IME)
            Ime
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PREZIME)
            Prezime
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SPOL)
            Spol
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KONTAKT_BROJ)
            Kontakt (mob/tel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EMAIL)
            e-mail
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ID_ULICA)
            Ulica
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ID_NASELJE)
            Naselje
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ID_MJESTO)
            Mjesto
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ROLA.OPIS)
            Vrsta osobe
        </th>
        <th></th>
    </tr>
</table>*@


@*@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.OIB)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IME)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PREZIME)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SPOL)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.KONTAKT_BROJ)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EMAIL)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ID_ULICA)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ID_NASELJE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ID_MJESTO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ROLA.OPIS)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID_OSOBA }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID_OSOBA }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID_OSOBA })
        </td>
    </tr>
}
*@

<br>
<br>

<div class="container content">
    <div class="row">
        <!-- Pricing -->

@foreach (var item in Model)
{

        <div class="col-md-3">
            <div class="pricing hover-effect">
                <div class="pricing-head">
                    <h3>
                        @Html.DisplayFor(modelItem => item.PREZIME)  @Html.DisplayFor(modelItem => item.IME)
                         <span>
                             *****
                        </span>
                    </h3>
                    <h4>
                       <i> @Html.DisplayFor(modelItem => item.OIB)</i>
                        <span>
                            @Html.DisplayFor(modelItem => item.ROLA.OPIS)
                        </span>
                    </h4>
                </div>

                <ul class="pricing-content list-unstyled">
                    <li>
                        Kontakt: @Html.DisplayFor(modelItem => item.KONTAKT_BROJ)
                    </li>
                    <li>
                        E-mail: @Html.DisplayFor(modelItem => item.EMAIL)
                    </li>
                </ul>

                <div class="pricing-footer">
                    <p>
                       
                    </p>
                    <div>
                        <a href="@Url.Action("Edit", "Osoba", new { id = item.ID_OSOBA })" class="btn btn-default btn-block">
                           Uredi podatke
                        </a>
                    </div>
                    <div>
                        <a href="@Url.Action("Details", "Osoba", new { id = item.ID_OSOBA })" class="btn btn-default btn-block">
                           Pregledaj detalje
                        </a>
                        @*@Html.ActionLink("Details", "Details", new { id = item.ID_OSOBA })*@
                    </div>
                    <div>
                        <a href="@Url.Action("Delete", "Osoba", new { id = item.ID_OSOBA })" class="btn btn-default btn-block">
                           Obriši osobu
                        </a>
                        @*@Html.ActionLink("Delete", "Delete", new { id = item.ID_OSOBA })*@
                    </div>
                </div>
            </div>
        </div>
}
        <!--//End Pricing -->
    </div>
</div>



<!-- Modal -->
<div id="myModal" class="modal fade" role="form">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Osoba</h4>
            </div>
            <div class="modal-body">

                @*@{Html.RenderAction("Create", "VrstaSpisa");}*@
                <div id="modalWrapper"></div>

            </div>

            @*<div class="modal-footer">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                        <div>
                            @Html.ActionLink("Back to List", "Index")
                        </div>
                    </div> proba
                </div>*@
        </div>

    </div>
</div>

<br>
<br>
<center>
    <strong>Powered by <a href="http://www.google.com" target="_blank">eHO-KU, kortikultura</a></strong>
</center>
<br>
<br>