EHOKU/Controllers/PosaoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EHOKU.Models;


namespace EHOKU.Controllers
{
    public class PosaoController : Controller
    {
        private EHOKUEntities db = new EHOKUEntities();

        // GET: Posao
        public ActionResult Index()
        {
            //varijabla generirana
            ViewBag.ID_STATUS_POSLA = new SelectList(db.STATUS_POSLA, "ID_STATUS_POSLA", "OPIS");
            int v_Osoba = Convert.ToInt32(Osoba.Currentuser.ID);
            int v_OsobaRola = Convert.ToInt32(Osoba.Currentuser.ROLA);

            if (v_OsobaRola == 2)
            {
                var pOSAO = db.POSAO.Where(a => a.ID_VODITELJ == v_Osoba || a.ID_VODITELJ == null).Include(p => p.OSOBA).Include(p => p.OSOBA1).Include(p => p.OSOBA2).Include(p => p.STATUS_POSLA).Include(p => p.TIP_POSLA).OrderByDescending(p => p.DATUM_OBJAVE);

                return View(pOSAO.ToList());

            }
            else if(v_OsobaRola == 3 || v_OsobaRola == 4)
            {
                var pOSAO = db.POSAO.Where(a => a.ID_RADNIK == v_Osoba || a.ID_RADNIK == null).Include(p => p.OSOBA).Include(p => p.OSOBA1).Include(p => p.OSOBA2).Include(p => p.STATUS_POSLA).Include(p => p.TIP_POSLA).OrderByDescending(p => p.DATUM_OBJAVE);

                return View(pOSAO.ToList());

            }
            else
            {
                var pOSAO = db.POSAO.Include(p => p.OSOBA).Include(p => p.OSOBA1).Include(p => p.OSOBA2).Include(p => p.STATUS_POSLA).Include(p => p.TIP_POSLA).OrderByDescending(p => p.DATUM_OBJAVE);

                return View(pOSAO.ToList());
            }

        }

        //AKCIJA ZA FILTRIRANJE I PRETRAŽIVANJE
        [HttpPost]
        public ActionResult Index(int? ID_STATUS_POSLA, string searchString)
        {

            ViewBag.ID_STATUS_POSLA = new SelectList(db.STATUS_POSLA, "ID_STATUS_POSLA", "OPIS");
            int v_Osoba = Convert.ToInt32(Osoba.Currentuser.ID);
            int v_OsobaRola = Convert.ToInt32(Osoba.Currentuser.ROLA);
     
           
         
            if (v_OsobaRola == 2)
            {
                IEnumerable<POSAO> posao = db.POSAO.Where(a => a.ID_STATUS_POSLA == ID_STATUS_POSLA || ID_STATUS_POSLA == null).Where(a => a.ID_VODITELJ == v_Osoba || a.ID_VODITELJ == null).Where(x => x.OPIS_POSLA.Contains(searchString)).OrderByDescending(p => p.DATUM_OBJAVE);

                return View(posao);

            }
            else if (v_OsobaRola == 3 || v_OsobaRola == 4)
            {
                IEnumerable<POSAO> posao = db.POSAO.Where(a => a.ID_STATUS_POSLA == ID_STATUS_POSLA || ID_STATUS_POSLA == null).Where(a => a.ID_RADNIK == v_Osoba || a.ID_RADNIK == null).Where(x => x.OPIS_POSLA.Contains(searchString)).OrderByDescending(p => p.DATUM_OBJAVE);

                return View(posao);

            }
            else
            {
                IEnumerable<POSAO> posao = db.POSAO.Where(a => a.ID_STATUS_POSLA == ID_STATUS_POSLA || ID_STATUS_POSLA == null).Where(x => x.OPIS_POSLA.Contains(searchString)).OrderByDescending(p => p.DATUM_OBJAVE);

                return View(posao);
            }
        }



        // GET: Posao/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            POSAO pOSAO = db.POSAO.Find(id);
            if (pOSAO == null)
            {
                return HttpNotFound();
            }
            return View(pOSAO);
        }

        // GET: Posao/Create
        public ActionResult Create()
        {
            var v_osoba = db.OSOBA.Where(g => g.ID_ROLA == 5).OrderBy(g => g.IME).ToList().Select(x => new SelectListItem { Value = x.ID_OSOBA.ToString(), Text = x.IME + " " + x.PREZIME});
            //IEnumerable<SelectListItem> selectList = from g in v_osoba
            //                                         select new SelectListItem
            //                                         {
            //                                             Value = g.ID_OSOBA.ToString(),
            //                                             Text = g.IME + " " + g.PREZIME.ToString()
            //                                         };
            ViewBag.ID_KLIJENT = new SelectList(v_osoba, "Value", "Text");

            var v_osoba1 = db.OSOBA.Where(g => g.ID_ROLA == 3 || g.ID_ROLA == 4).OrderBy(g => g.IME).ToList();
            IEnumerable<SelectListItem> selectList1 = from g in v_osoba1
                                                     select new SelectListItem
                                                     {
                                                         Value = g.ID_OSOBA.ToString(),
                                                         Text = g.IME + " " + g.PREZIME.ToString()
                                                     };
            ViewBag.ID_RADNIK = new SelectList(selectList1, "Value", "Text");

            var v_osoba2 = db.OSOBA.Where(g => g.ID_ROLA == 2).OrderBy(g => g.IME).ToList();
            IEnumerable<SelectListItem> selectList2 = from g in v_osoba2
                                                      select new SelectListItem
                                                      {
                                                          Value = g.ID_OSOBA.ToString(),
                                                          Text = g.IME + " " + g.PREZIME.ToString()
                                                      };
            ViewBag.ID_VODITELJ = new SelectList(selectList2, "Value", "Text");

        
            //ViewBag.ID_KLIJENT = new SelectList(db.OSOBA.Where(g => g.ID_ROLA == 5), "ID_OSOBA", "IME");
            //ViewBag.ID_RADNIK = new SelectList(db.OSOBA.Where(g => g.ID_ROLA == 3), "ID_OSOBA", "IME");
            //ViewBag.ID_VODITELJ = new SelectList(db.OSOBA.Where(g => g.ID_ROLA == 1), "ID_OSOBA", "IME");
            ViewBag.ID_STATUS_POSLA = new SelectList(db.STATUS_POSLA, "ID_STATUS_POSLA", "OPIS");
            ViewBag.ID_TIP_POSLA = new SelectList(db.TIP_POSLA, "ID_TIP_POSLA", "OPIS");
            return View();
        }



        // POST: Posao/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_POSAO,ID_STATUS_POSLA,ID_KLIJENT,ID_VODITELJ,ID_RADNIK,VRIJEME_POCETKA,VRIJEME_ZAVRSETKA,ROK_IZVEDBE,IZNOS,NAPLACENO,ISPLACENO,OCJENA_OBJAVLJENOG_POSLA,NAPOMENA,OPIS_POSLA,PRILOG,ID_TIP_POSLA")] POSAO pOSAO)
        {

                int v_Osoba = Convert.ToInt32(Osoba.Currentuser.ROLA);
                decimal v1_Osoba = Convert.ToDecimal(Osoba.Currentuser.ID);


            if (ModelState.IsValid)
                {
                    pOSAO.ID_VODITELJ = v1_Osoba;
                    db.POSAO.Add(pOSAO);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
           
            ViewBag.ID_KLIJENT = new SelectList(db.OSOBA, "ID_OSOBA", "IME", pOSAO.ID_KLIJENT);
            ViewBag.ID_RADNIK = new SelectList(db.OSOBA, "ID_OSOBA", "IME", pOSAO.ID_RADNIK);
            ViewBag.ID_VODITELJ = new SelectList(db.OSOBA, "ID_OSOBA", "IME", pOSAO.ID_VODITELJ);
            ViewBag.ID_STATUS_POSLA = new SelectList(db.STATUS_POSLA, "ID_STATUS_POSLA", "OPIS", pOSAO.ID_STATUS_POSLA);
            ViewBag.ID_TIP_POSLA = new SelectList(db.TIP_POSLA, "ID_TIP_POSLA", "OPIS", pOSAO.ID_TIP_POSLA);
            return View(pOSAO);
        }

        // GET: Posao/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            POSAO pOSAO = db.POSAO.Find(id);
            if (pOSAO == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_KLIJENT = new SelectList(db.OSOBA, "ID_OSOBA", "IME", pOSAO.ID_KLIJENT);
            ViewBag.ID_RADNIK = new SelectList(db.OSOBA, "ID_OSOBA", "IME", pOSAO.ID_RADNIK);
            ViewBag.ID_VODITELJ = new SelectList(db.OSOBA, "ID_OSOBA", "IME", pOSAO.ID_VODITELJ);
            ViewBag.ID_STATUS_POSLA = new SelectList(db.STATUS_POSLA, "ID_STATUS_POSLA", "OPIS", pOSAO.ID_STATUS_POSLA);
            ViewBag.ID_TIP_POSLA = new SelectList(db.TIP_POSLA, "ID_TIP_POSLA", "OPIS", pOSAO.ID_TIP_POSLA);
            return View(pOSAO);
        }

        // POST: Posao/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_POSAO,ID_STATUS_POSLA,ID_KLIJENT,ID_VODITELJ,ID_RADNIK,VRIJEME_POCETKA,VRIJEME_ZAVRSETKA,ROK_IZVEDBE,IZNOS,NAPLACENO,ISPLACENO,OCJENA_OBJAVLJENOG_POSLA,NAPOMENA,OPIS_POSLA,PRILOG,ID_TIP_POSLA")] POSAO pOSAO)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pOSAO).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_KLIJENT = new SelectList(db.OSOBA, "ID_OSOBA", "IME", pOSAO.ID_KLIJENT);
            ViewBag.ID_RADNIK = new SelectList(db.OSOBA, "ID_OSOBA", "IME", pOSAO.ID_RADNIK);
            ViewBag.ID_VODITELJ = new SelectList(db.OSOBA, "ID_OSOBA", "IME", pOSAO.ID_VODITELJ);
            ViewBag.ID_STATUS_POSLA = new SelectList(db.STATUS_POSLA, "ID_STATUS_POSLA", "OPIS", pOSAO.ID_STATUS_POSLA);
            ViewBag.ID_TIP_POSLA = new SelectList(db.TIP_POSLA, "ID_TIP_POSLA", "OPIS", pOSAO.ID_TIP_POSLA);

EHOKU/Views/Posao/Create.cshtml
@model EHOKU.Controllers.POSAO
@using EHOKU.Models;

@{
    ViewBag.Title = "Create";
    Layout = null;
}


@*@using (Html.BeginForm()) 
{*@

@using (Html.BeginForm("Create", "Posao", FormMethod.Post, new { @class = "form-horizontal" }))
{
@Html.AntiForgeryToken()
    
    @*<div class="form-horizontal">*@
    <div class="row">

        <div class="form-group">
            <label class="col-md-3 control-label">Vrsta posla:</label>
            <div class="col-md-6">                
                @Html.DropDownList("ID_TIP_POSLA", null, htmlAttributes: new { @class = "form-control" }, optionLabel: "Odaberite vrstu posla")
                @Html.ValidationMessageFor(model => model.ID_TIP_POSLA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Klijent:</label>
            <div class="col-md-6 center-block text-center">
                @Html.DropDownList("ID_KLIJENT", null, htmlAttributes: new { @class = "form-control" }, optionLabel: "Odaberite klijenta")
                @Html.ValidationMessageFor(model => model.ID_KLIJENT, "", new { @class = "text-danger" })
            </div>
        </div>
        
            @*<div class="form-group">
                <label class="col-md-3 control-label">Voditelj posla:</label>
                <div class="col-md-6 center-block text-center">
                    @Html.DropDownList("ID_VODITELJ", null, htmlAttributes: new { @class = "form-control" }, optionLabel: "Odaberite voditelja posla")
                    @Html.ValidationMessageFor(model => model.ID_VODITELJ, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <label class="col-md-3 control-label">Radnik:</label>
            <div class="col-md-6 center-block text-center">   
                @Html.DropDownList("ID_RADNIK", null, htmlAttributes: new { @class = "form-control" }, optionLabel: "Odaberite radnika ili ostavite prazno")
                @Html.ValidationMessageFor(model => model.ID_RADNIK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Rok izvedbe:</label>
            <div class="col-md-6 center-block text-center">
                @Html.EditorFor(model => model.ROK_IZVEDBE, new { htmlAttributes = new { @class = "form-control", id= "datetimepicker" } })
                @Html.ValidationMessageFor(model => model.ROK_IZVEDBE, "", new { @class = "text-danger", placeholder = "Unesite datum roka" })
            </div>
            <script type="text/javascript">
            $(function () {
                $('#datetimepicker').datetimepicker();
            });
            </script>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Ugovoreni iznos:</label>
            <div class="col-md-6 center-block text-center"> 
                @Html.EditorFor(model => model.IZNOS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IZNOS, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.NAPLACENO, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NAPLACENO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NAPLACENO, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.ISPLACENO, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ISPLACENO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ISPLACENO, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.OCJENA_OBJAVLJENOG_POSLA, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OCJENA_OBJAVLJENOG_POSLA, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.OCJENA_OBJAVLJENOG_POSLA, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <label class="col-md-3 control-label">Opis posla:</label>
            <div class="col-md-6 center-block text-center">
                @Html.EditorFor(model => model.OPIS_POSLA, new { htmlAttributes = new { @class = "form-control", placeholder = "Opis posla" } })
                @Html.ValidationMessageFor(model => model.OPIS_POSLA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Prilog:</label>
            <div class="col-md-6 center-block text-center">
                @Html.EditorFor(model => model.PRILOG, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PRILOG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-6">
                <br>
                <input type="submit" value="Izradi posao" class="btn btn-success btn-block" />
            </div>
        </div>
    </div>
}


@*<script>
    $(document).ready(function () {
        $('#datetimepicker').datetimepicker({
            language: "HR"
        });
    });
</script>*@


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EHOKU/Views/Posao/Delete.cshtml
@model EHOKU.Controllers.POSAO

@{
    ViewBag.Title = "Delete";
    Layout = null;
}

@*<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>*@
<div>
    @*<h4>POSAO</h4>
    <hr />*@
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.VRIJEME_POCETKA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VRIJEME_POCETKA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VRIJEME_ZAVRSETKA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VRIJEME_ZAVRSETKA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ROK_IZVEDBE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ROK_IZVEDBE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IZNOS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IZNOS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NAPLACENO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NAPLACENO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ISPLACENO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ISPLACENO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OCJENA_OBJAVLJENOG_POSLA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OCJENA_OBJAVLJENOG_POSLA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NAPOMENA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NAPOMENA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OPIS_POSLA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OPIS_POSLA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRILOG)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PRILOG)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OSOBA.IME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OSOBA.IME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OSOBA1.IME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OSOBA1.IME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OSOBA2.IME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OSOBA2.IME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.STATUS_POSLA.OPIS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.STATUS_POSLA.OPIS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TIP_POSLA.OPIS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TIP_POSLA.OPIS)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @*@Html.ActionLink("Back to List", "Index")*@
        </div>
    }
</div>

EHOKU/Views/Posao/Details.cshtml
@model EHOKU.Controllers.POSAO

@{
    ViewBag.Title = "Details";
    Layout = null;
}



<div>
    <dl class="dl-horizontal">

        <dt>
            Tip posla:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TIP_POSLA.OPIS)
        </dd>

        <dt>
            Status posla:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.STATUS_POSLA.OPIS)
        </dd>

        <dt>
            Datum objave posla:
        </dt>

        <dd>
            @Convert.ToString(string.Format("{0:dd/MM/yyyy}", Model.DATUM_OBJAVE))
        </dd>

        <dt>
            Rok izvedbe posla:
        </dt>

        <dd>
            @Convert.ToString(string.Format("{0:dd/MM/yyyy}", Model.ROK_IZVEDBE))
        </dd>

        <dt>
            Iznos posla:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IZNOS) Kuna
        </dd>

        <dt>
           Napomena:
        </dt>
           
        <dd>
            @Html.DisplayFor(model => model.NAPOMENA)
        </dd>

        <dt>
            Opis posla:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OPIS_POSLA)
        </dd>
      
        <dt>
            Voditelj:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OSOBA2.IME) @Html.DisplayFor(model => model.OSOBA2.PREZIME)
        </dd>

        <dt>
            Radnik:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OSOBA1.IME) @Html.DisplayFor(model => model.OSOBA1.PREZIME)
        </dd>
        <hr />
        <dt>
            Ime klijenta:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OSOBA.IME) @Html.DisplayFor(model => model.OSOBA.PREZIME)
        </dd>

        <dt>
            Adresa klijenta:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OSOBA.MJESTO) @Html.DisplayFor(model => model.OSOBA.ULICA)
        </dd>

        <dt>
            Geo - pozicija:
        </dt>

        <dd>
            Latitude: @Html.DisplayFor(model => model.OSOBA.LATITUDE) 
            Longitude: @Html.DisplayFor(model => model.OSOBA.LONGITUDE)
        </dd>
        <div class="form-group">
            <div class="col-md-offset-3 col-md-6">
                <br>
                <a class="btn btn-success btn-block" href=@("https://www.google.hr/maps/@" + Model.OSOBA.LONGITUDE+"," + Model.OSOBA.LATITUDE + ",19.75z") target="_blank"><span>Google maps - GeoPozicija</span></a>
                <a class="btn btn-success btn-block" href=@("https://maps.google.com?q=" + Model.OSOBA.ULICA.Replace(" ", "+") + "+" + Model.OSOBA.MJESTO.Replace(" ", "+")) target="_blank"><span>Google maps - Adresa</span></a>
                <a class="btn btn-success btn-block" href=@("https://maps.google.com?saddr=Current+Location&daddr=" + Model.OSOBA.ULICA.Replace(" ", "+") + "+" + Model.OSOBA.MJESTO.Replace(" ", "+") + "+Hrvatska") target="_blank"><span>Google maps - Ruta</span></a>
                <br>
                <br>
                <br>
            </div>
        </div>
        <hr />
        <br>
        <br>
    </dl>
</div>



@*<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_POSAO }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@

EHOKU/Views/Posao/OcijeniPosao.cshtml
@model EHOKU.Controllers.POSAO

@{
    ViewBag.Title = "OcijeniPosao";
    Layout = null;
}
@{
    List<SelectListItem> listItems = new List<SelectListItem>();
    listItems.Add(new SelectListItem
    {
        Text = "1",
        Value = "1"
    });
    listItems.Add(new SelectListItem
    {
        Text = "2",
        Value = "2"
    });
    listItems.Add(new SelectListItem
    {
        Text = "3",
        Value = "3"
    });
    listItems.Add(new SelectListItem
    {
        Text = "4",
        Value = "4"
    });
    listItems.Add(new SelectListItem
    {
        Text = "5",
        Value = "5"
    });
}
<style>
select_lista {
    width: 250px;
}
</style>





@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_POSAO)


            <h4 align="center" >Napomena radnika o završenom poslu</h4> 
        <div class="col-lg-12">
            @Html.DisplayFor(model => model.NAPOMENA)
         </div>
        <br>
        <hr />

            <div class="form-group">
                <div class="col-lg-6 col-lg-offset-3">
                    @*@Html.EditorFor(model => model.OCJENA_OBJAVLJENOG_POSLA, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.DropDownListFor(model => model.OCJENA_OBJAVLJENOG_POSLA, listItems, "Odaberite ocjenu za posao", new { style = "width: 270px;" })
                    @Html.ValidationMessageFor(model => model.OCJENA_OBJAVLJENOG_POSLA, "", new { @class = "text-danger" })
                </div>
            </div>

            
            <div class="form-group">
                <div class="col-md-offset-3 col-md-6">
                    <br>
                    <input type="submit" value="Ocijeni posao" class="btn btn-success btn-block" />
                </div>
            </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EHOKU/Views/Posao/PrihvatioPosao.cshtml
@{
    ViewBag.Title = "PrihvatioPosao";
}

<h2>PrihvatioPosao</h2>

EHOKU/Views/Posao/ZavrsiPosao.cshtml
@model EHOKU.Controllers.POSAO

@{
    ViewBag.Title = "ZavrsiPosao";
    Layout = null;
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_POSAO)

        <div class="form-group">
            <label class="col-md-3 control-label">Datum početka:</label>
            <div class="col-lg-6">
                @Html.EditorFor(model => model.VRIJEME_POCETKA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VRIJEME_POCETKA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Datum završetka:</label>
            <div class="col-lg-6">
                @Html.EditorFor(model => model.VRIJEME_ZAVRSETKA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VRIJEME_ZAVRSETKA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Napomena:</label>
            <div class="col-lg-6">
                @Html.EditorFor(model => model.NAPOMENA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NAPOMENA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-6">
                <br>
                <input type="submit" value="Završi posao" class="btn btn-success btn-block" />
            </div>
        </div>
    </div>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}